name: mythic_gme_adventures
description: Mythic GME Adventures
publish_to: 'none'
version: 1.8.0+15

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  animated_list_plus: ^0.5.2
  archive: ^4.0.1
  catcher_2: ^2.0.1
  collection: ^1.18.0
  cross_file: ^0.3.4+2
  extension_google_sign_in_as_googleapis_auth: ^2.0.11
  #file_picker: ^8.1.5
  # TODO restore pubdev when this is fixed: https://github.com/miguelpruivo/flutter_file_picker/issues/1643
  file_picker:
    git:
      url: https://github.com/abdelaziz-mahdy/flutter_file_picker
      ref: fix-flutter-3.27-compile-error
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.2
  flutter_hooks: ^0.20.3
  flutter_secure_storage: ^9.0.0
  flutter_web_auth_2: ^4.0.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  googleapis: ^13.2.0
  googleapis_auth: ^1.4.1
  http: ^1.1.2
  intl: any
  io: ^1.0.4
  loggy: ^2.0.3
  package_info_plus: ^8.0.0
  path_provider: ^2.1.1
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  web: ^1.1.0
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true

  assets:
    - assets/meaning_tables/en/
    - assets/meaning_tables/fr/
    - assets/google_fonts/