name: mythic_gme_adventures
description: Mythic GME Adventures
publish_to: 'none'
version: 1.2.1+7

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  catcher_2: ^1.0.4
  collection: ^1.17.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.11
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.2
  flutter_hooks: ^0.20.3
  flutter_secure_storage: ^9.0.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  http: ^1.1.2
  intl: any
  io: ^1.0.4
  loggy: ^2.0.3
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  window_manager: ^0.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true

  assets:
    - assets/meaning_tables/en/
    - assets/meaning_tables/fr/
    - assets/google_fonts/