name: mythic_gme_adventures
description: Mythic GME Adventures
publish_to: 'none'
version: 1.13.0+23

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  animated_list_plus: ^0.5.2
  archive: ^4.0.2
  catcher_2: ^2.0.1
  collection: ^1.18.0
  cross_file: ^0.3.4+2
  extension_google_sign_in_as_googleapis_auth: ^2.0.11
  file_picker: ^10.0.0
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.2
  flutter_hooks: ^0.21.2
  flutter_quill: ^11.4.2
  flutter_secure_storage: ^9.0.0
  flutter_web_auth_2: ^4.0.1
  formatted_text: ^4.0.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.1.2
  intl: any
  io: ^1.0.4
  loggy: ^2.0.3
  package_info_plus: ^8.0.0
  path_provider: ^2.1.1
  rxdart: ^0.28.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  web: ^1.1.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/meaning_tables/en/
    - assets/meaning_tables/fr/
    - assets/meaning_tables/pt/
    - assets/google_fonts/